## Для начала считаем csv и уберем колонку link

In [1]:
import pandas as pd

In [2]:
chess_data_all=pd.read_csv('data/csv/chess.csv')

In [3]:
chess_data_all.head(5)

a8  b8  c8   d8    e8  f8  g8  h8  a7  b7  ...    e1  f1  g1  h1  \
0 -60 -45 -40 -100 -1000   0   0 -60 -20 -20  ...  1000   0  45  60   
1 -60 -45 -40 -100 -1000   0   0 -60 -20 -20  ...  1000   0  45  60   
2 -60 -45 -40 -100 -1000   0   0 -60 -20   0  ...  1000   0  45  60   
3 -60   0 -40    0 -1000 -40   0 -60 -20 -20  ...  1000   0   0  60   
4 -60   0 -40    0 -1000 -40   0 -60 -20 -20  ...  1000   0   0  60   

   whose_move  casting_white  casting_black  pawn  res  \
0           2              6              6     0  450   
1           1              6              6     0  550   
2           1              6              6     0  550   
3           1              6              6     0 -650   
4           2              6              6     0 -640   

                                                link  
0  https://www.chess.com/analysis/game/master/157...  
1  https://www.chess.com/analysis/game/master/157...  
2  https://www.chess.com/analysis/game/master/157...  
3  https://www.chess.com/analysis/game/master/157...  
4  https://www.chess.com/analysis/game/master/157...  

[5 rows x 70 columns]

In [4]:
x_columns=['a8','b8','c8','d8','e8','f8','g8','h8',
    'a7','b7','c7','d7','e7','f7','g7','h7',
    'a6','b6','c6','d6','e6','f6','g6','h6',
    'a5','b5','c5','d5','e5','f5','g5','h5',
    'a4','b4','c4','d4','e4','f4','g4','h4',
    'a3','b3','c3','d3','e3','f3','g3','h3',
    'a2','b2','c2','d2','e2','f2','g2','h2',
    'a1','b1','c1','d1','e1','f1','g1','h1',
    'whose_move','casting_white','casting_black','pawn']
y_column=['res']

In [5]:
X=chess_data_all[x_columns]
y=chess_data_all[y_column]

In [7]:
X.head(5)

a8  b8  c8   d8    e8  f8  g8  h8  a7  b7  ...  c1   d1    e1  f1  g1  h1  \
0 -60 -45 -40 -100 -1000   0   0 -60 -20 -20  ...  40  100  1000   0  45  60   
1 -60 -45 -40 -100 -1000   0   0 -60 -20 -20  ...  40    0  1000   0  45  60   
2 -60 -45 -40 -100 -1000   0   0 -60 -20   0  ...  40    0  1000   0  45  60   
3 -60   0 -40    0 -1000 -40   0 -60 -20 -20  ...  40    0  1000   0   0  60   
4 -60   0 -40    0 -1000 -40   0 -60 -20 -20  ...  40    0  1000   0   0  60   

   whose_move  casting_white  casting_black  pawn  
0           2              6              6     0  
1           1              6              6     0  
2           1              6              6     0  
3           1              6              6     0  
4           2              6              6     0  

[5 rows x 68 columns]

In [8]:
y.head(5)

res
0  450
1  550
2  550
3 -650
4 -640

### Разделим данные на обучающую выборку и тестовую

In [9]:
X_train=X[:-20]
X_test=X[-20:]

In [10]:
X_test

a8  b8  c8   d8    e8  f8  g8  h8  a7  b7  ...  c1   d1    e1  f1  g1  \
269 -60   0 -40 -100 -1000 -40 -45 -60 -20 -20  ...  40  100  1000  40   0   
270 -60   0 -40 -100 -1000 -40 -45 -60 -20 -20  ...  40  100  1000   0   0   
271 -60   0 -40    0 -1000 -40 -45 -60 -20 -20  ...  40  100  1000   0   0   
272 -60   0 -40    0 -1000 -40 -45 -60 -20 -20  ...  40  100  1000   0   0   
273 -60   0 -40    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
274 -60   0 -40    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
275 -60   0 -40    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
276 -60   0 -40    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
277 -60   0 -40    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
278 -60   0 -40    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
279 -60   0 -40    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
280  60   0 -40    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
281  60   0 -40    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
282   0   0  60    0 -1000 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
283   0   0  60    0     0 -40 -45 -60   0 -20  ...  40  100  1000   0   0   
284   0   0   0    0     0  60 -45 -60   0 -20  ...  40  100  1000   0   0   
285   0   0   0    0     0  60 -45 -60   0 -20  ...  40  100  1000   0   0   
286   0   0   0    0     0  60 -45 -60   0 -20  ...  40  100  1000  45   0   
287   0   0   0    0     0  60 -45 -60   0 -20  ...  40  100  1000  45   0   
288   0   0   0    0     0  60 -45 -60   0 -20  ...  40  100  1000  45   0   

      h1  whose_move  casting_white  casting_black  pawn  
269   60           2              6              6     0  
270   60           1              6              6     0  
271   60           2              6              6     0  
272   60           1              6              6     2  
273   60           2              6              6     0  
274   60           1              6              6     0  
275   60           2              6              6     0  
276   60           1              6              6     0  
277   60           2              6              6     0  
278   60           1              6              6     0  
279   60           2              6              6     0  
280   60           1              3              3     0  
281   60           2              3              3     0  
282   60           1              3              3     0  
283   60           2              3              1     0  
284   60           1              3              1     0  
285 -100           2              1              1     0  
286 -100           1              1              1     0  
287 -100           2              1              1     0  
288 -100           1              1              1     0  

[20 rows x 68 columns]

In [12]:
X_train

a8  b8  c8   d8    e8  f8  g8  h8  a7  b7  ...  c1   d1    e1  f1    g1  \
0   -60 -45 -40 -100 -1000   0   0 -60 -20 -20  ...  40  100  1000   0    45   
1   -60 -45 -40 -100 -1000   0   0 -60 -20 -20  ...  40    0  1000   0    45   
2   -60 -45 -40 -100 -1000   0   0 -60 -20   0  ...  40    0  1000   0    45   
3   -60   0 -40    0 -1000 -40   0 -60 -20 -20  ...  40    0  1000   0     0   
4   -60   0 -40    0 -1000 -40   0 -60 -20 -20  ...  40    0  1000   0     0   
..   ..  ..  ..  ...   ...  ..  ..  ..  ..  ..  ...  ..  ...   ...  ..   ...   
264 -60   0 -40    0 -1000   0   0 -60 -20   0  ...   0    0     0  60  1000   
265 -60   0 -40    0 -1000   0   0 -60 -20   0  ...   0    0     0  60  1000   
266 -60   0 -40    0 -1000   0   0 -60 -20   0  ...   0    0     0  60  1000   
267 -60 -45 -40 -100 -1000 -40 -45 -60 -20 -20  ...  40  100  1000  40    45   
268 -60 -45 -40 -100 -1000 -40 -45 -60 -20 -20  ...  40  100  1000  40     0   

     h1  whose_move  casting_white  casting_black  pawn  
0    60           2              6              6     0  
1    60           1              6              6     0  
2    60           1              6              6     0  
3    60           1              6              6     0  
4    60           2              6              6     0  
..   ..         ...            ...            ...   ...  
264   0           1              1              6     0  
265   0           2              1              6     0  
266   0           1              1              6     0  
267  60           2              6              6    21  
268  60           1              6              6     0  

[269 rows x 68 columns]

In [13]:
y_train=y[:-20]
y_test=y[-20:]

In [22]:
X_train.to_numpy()

array([[-60, -45, -40, ...,   6,   6,   0],
       [-60, -45, -40, ...,   6,   6,   0],
       [-60, -45, -40, ...,   6,   6,   0],
       ...,
       [-60,   0, -40, ...,   1,   6,   0],
       [-60, -45, -40, ...,   6,   6,  21],
       [-60, -45, -40, ...,   6,   6,   0]])

### Пробуем обучить данные

In [24]:
from sklearn import svm

In [37]:
from sklearn.ensemble import RandomForestRegressor

In [56]:
regressor = RandomForestRegressor(n_estimators=40, random_state=0)

In [57]:
regressor.fit(X_train, y_train)

<ipython-input-57-cb9aa30858d7>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train, y_train)


RandomForestRegressor(n_estimators=40, random_state=0)

In [58]:
regressor.predict(X_test)

array([  48.66666667,   27.89583333, 2665.625     , 2680.625     ,
       2665.1875    , 3047.4375    , 3033.4375    , 3048.4375    ,
        127.75      ,  121.625     ,  146.5       ,  137.5       ,
        344.25      ,  341.5       ,  358.9       ,  354.025     ,
        248.4       ,  222.56666667,  253.5       ,  182.66666667])

In [52]:
y_test.to_numpy().T[0]

array([  70,  -30,   70,  -10,   20,  -50,  -50,  -50,  740,  730,  880,
        890, 1000,  990, 1000, 1000, 1000,  890, 1300, 1300])